// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ptz-dashboard/BroadcastConsole.tsx": () => import("../components/mockups/ptz-dashboard/BroadcastConsole.tsx"),
  "./components/mockups/ptz-dashboard/CommandCenter.tsx": () => import("../components/mockups/ptz-dashboard/CommandCenter.tsx"),
  "./components/mockups/ptz-dashboard/StudioGlass.tsx": () => import("../components/mockups/ptz-dashboard/StudioGlass.tsx")
};
